export const villages = {
  bishnupur: {
    name: "Bishnupur Village",
    population: 1250,
    households: 320,
    issues: 5,
    nextEvent: {
      title: "Gram Panchayat Meeting",
      date: "Sunday, 15 Oct 2023 - 10:00 AM",
      location: "Panchayat Office",
      description: "Monthly meeting to discuss village development projects and budget allocation.",
    },
    alerts: [
      {
        type: "urgent",
        icon: '<i class="fas fa-tint"></i>',
        title: "Water Supply Disruption",
        description: "Water supply will be disrupted for 6 hours due to pipeline repair",
        time: "2 hours ago",
      },
      {
        type: "normal",
        icon: '<i class="fas fa-calendar-alt"></i>',
        title: "Vaccination Camp",
        description: "Polio vaccination camp at village center on Sunday",
        time: "Yesterday",
      },
      {
        type: "normal",
        icon: '<i class="fas fa-road"></i>',
        title: "Road Repair",
        description: "Main road to market will be under repair for 3 days",
        time: "2 days ago",
      },
    ],
    activeIssues: [
      {
        id: 1,
        title: "Water Pipeline Leakage",
        category: "water",
        location: "North Side",
        status: "pending",
        reporter: "Ramesh Patil",
        date: "10 Oct 2023",
        description: "Major water leakage near the northern water tank affecting 20 households",
        progress: "Issue reported to water committee. Technician scheduled to visit tomorrow.",
        supporters: 15,
      },
      {
        id: 2,
        title: "Street Light Failure",
        category: "electricity",
        location: "Village Center",
        status: "pending",
        reporter: "Sunita Jadhav",
        date: "8 Oct 2023",
        description: "5 street lights not working in the market area making it unsafe at night",
        progress: "Electrician notified. Parts being ordered from district headquarters.",
        supporters: 24,
      },
      {
        id: 3,
        title: "Garbage Collection Issues",
        category: "sanitation",
        location: "East Side",
        status: "pending",
        reporter: "Vijay Kumar",
        date: "5 Oct 2023",
        description: "No garbage collection for the past week in eastern part of village",
        progress: "Sanitation committee informed. Collection vehicle repair in progress.",
        supporters: 18,
      },
    ],
    resolvedIssues: [
      {
        id: 4,
        title: "School Roof Leakage",
        category: "infrastructure",
        location: "Village Center",
        status: "resolved",
        reporter: "Headmaster Deshmukh",
        date: "15 Sep 2023",
        description: "Leaking roof in primary school classrooms during monsoon",
        resolution: "Roof repaired and waterproofed on 25 Sep 2023",
        supporters: 45,
      },
      {
        id: 5,
        title: "Damaged Footbridge",
        category: "infrastructure",
        location: "West Side",
        status: "resolved",
        reporter: "Anand Sharma",
        date: "10 Sep 2023",
        description: "Wooden footbridge over stream damaged and unsafe to cross",
        resolution: "Bridge rebuilt with concrete structure on 30 Sep 2023",
        supporters: 38,
      },
    ],
    panchayatMembers: [
      {
        name: "Rajendra Singh",
        position: "Sarpanch",
        photo: "https://randomuser.me/api/portraits/men/44.jpg",
        phone: "9876543210",
        email: "rajendra.singh@example.com",
      },
      {
        name: "Lata Sharma",
        position: "Deputy Sarpanch",
        photo: "https://randomuser.me/api/portraits/women/65.jpg",
        phone: "9876543211",
        email: "lata.sharma@example.com",
      },
      {
        name: "Mohan Desai",
        position: "Panchayat Secretary",
        photo: "https://randomuser.me/api/portraits/men/32.jpg",
        phone: "9876543212",
        email: "mohan.desai@example.com",
      },
      {
        name: "Priya Kadam",
        position: "Member",
        photo: "https://randomuser.me/api/portraits/women/45.jpg",
        phone: "9876543213",
        email: "priya.kadam@example.com",
      },
      {
        name: "Sunil Patil",
        position: "Member",
        photo: "https://randomuser.me/api/portraits/men/67.jpg",
        phone: "9876543214",
        email: "sunil.patil@example.com",
      },
    ],
    panchayatDecisions: [
      {
        title: "Water Supply Timing Change",
        date: "2 Oct 2023",
        description: "Changed water supply timings to 6-8 AM and 5-7 PM",
        yesVotes: 4,
        noVotes: 1,
      },
      {
        title: "Solar Lights Installation",
        date: "15 Sep 2023",
        description: "Approved budget for 20 solar street lights in dark zones",
        yesVotes: 5,
        noVotes: 0,
      },
      {
        title: "School Building Expansion",
        date: "5 Sep 2023",
        description: "Approved plan to add 2 new classrooms to primary school",
        yesVotes: 3,
        noVotes: 2,
      },
    ],
    mediaGallery: [
      {
        id: 1,
        type: "event",
        title: "Independence Day Celebration",
        description: "Village gathered for flag hoisting and cultural performances",
        image:
          "https://images.unsplash.com/photo-1532375810709-75b1da00537c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
        date: "15 Aug 2023",
        postedBy: "Village Secretary",
        verifications: 45,
      },
      {
        id: 2,
        type: "news",
        title: "New Borewell Commissioned",
        description: "Additional water source now available for eastern part of village",
        image:
          "https://images.unsplash.com/photo-1581612129334-551ccd2c6a8a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
        date: "10 Sep 2023",
        postedBy: "Water Committee",
        verifications: 32,
      },
      {
        id: 3,
        type: "celebration",
        title: "Navratri Festival",
        description: "Nine nights of festivities and garba at village square",
        image:
          "https://images.unsplash.com/photo-1609159125019-b7c02b532c63?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80",
        date: "25 Sep 2023",
        postedBy: "Cultural Committee",
        verifications: 78,
      },
    ],
    activeInitiatives: [
      {
        id: 1,
        title: "Tree Plantation Drive",
        category: "environment",
        description: "Plant 500 trees along village roads and public spaces",
        target: 50,
        current: 35,
        startDate: "1 Oct 2023",
        initiator: "Anand Patil",
      },
      {
        id: 2,
        title: "Digital Learning Center",
        category: "education",
        description: "Set up a computer center for school children with 5 computers",
        target: 100,
        current: 68,
        startDate: "15 Sep 2023",
        initiator: "Headmaster Joshi",
      },
    ],
    completedInitiatives: [
      {
        id: 3,
        title: "Village Cleanup Drive",
        category: "sanitation",
        description: "Community effort to clean public spaces and improve waste management",
        target: 40,
        current: 53,
        startDate: "1 Aug 2023",
        completionDate: "15 Aug 2023",
        initiator: "Youth Club",
      },
      {
        id: 4,
        title: "Public Library Setup",
        category: "education",
        description: "Establish village library with 500 books for all age groups",
        target: 75,
        current: 89,
        startDate: "1 Jul 2023",
        completionDate: "30 Aug 2023",
        initiator: "Lata Sharma",
      },
    ],
  },
  chandpur: {
    name: "Chandpur Village",
    population: 890,
    households: 210,
    issues: 3,
    nextEvent: {
      title: "Agricultural Training",
      date: "Saturday, 21 Oct 2023 - 9:00 AM",
      location: "Village Hall",
      description: "Training session on organic farming techniques by district agriculture officer.",
    },
    alerts: [
      {
        type: "urgent",
        icon: '<i class="fas fa-exclamation-triangle"></i>',
        title: "Bridge Repair Warning",
        description: "Wooden bridge to farmlands unsafe - Use alternate route",
        time: "5 hours ago",
      },
      {
        type: "normal",
        icon: '<i class="fas fa-truck"></i>',
        title: "Fertilizer Distribution",
        description: "Subsidized fertilizer distribution starts tomorrow at co-op",
        time: "Yesterday",
      },
    ],
    activeIssues: [
      {
        id: 1,
        title: "Irrigation Canal Blockage",
        category: "water",
        location: "South Side",
        status: "pending",
        reporter: "Dinesh Patil",
        date: "12 Oct 2023",
        description: "Canal to southern fields blocked with debris after heavy rains",
        progress: "Pending assessment by irrigation department",
        supporters: 22,
      },
    ],
    resolvedIssues: [],
    panchayatMembers: [
      {
        name: "Prakash Jadhav",
        position: "Sarpanch",
        photo: "https://randomuser.me/api/portraits/men/72.jpg",
        phone: "9876543220",
        email: "prakash.jadhav@example.com",
      },
    ],
    panchayatDecisions: [],
    mediaGallery: [],
    activeInitiatives: [],
    completedInitiatives: [],
  },
  devgaon: {
    name: "Devgaon Village",
    population: 1560,
    households: 380,
    issues: 7,
    nextEvent: {
      title: "Health Awareness Camp",
      date: "Sunday, 22 Oct 2023 - 10:00 AM",
      location: "Primary Health Center",
      description: "Awareness camp on malaria prevention and seasonal diseases.",
    },
    alerts: [
      {
        type: "urgent",
        icon: '<i class="fas fa-virus"></i>',
        title: "Malaria Alert",
        description: "Increased malaria cases reported - Take precautions",
        time: "1 day ago",
      },
    ],
    activeIssues: [
      {
        id: 1,
        title: "Stagnant Water Puddles",
        category: "sanitation",
        location: "West Side",
        status: "pending",
        reporter: "Dr. Pawar",
        date: "12 Oct 2023",
        description: "Multiple areas of stagnant water increasing mosquito breeding",
        progress: "Health department inspection scheduled for tomorrow",
        supporters: 42,
      },
    ],
    resolvedIssues: [],
    panchayatMembers: [],
    panchayatDecisions: [],
    mediaGallery: [],
    activeInitiatives: [],
    completedInitiatives: [],
  },
  amritpur: {
    name: "Amritpur Village",
    population: 720,
    households: 175,
    issues: 4,
    nextEvent: {
      title: "Village Women's Meeting",
      date: "Monday, 16 Oct 2023 - 3:00 PM",
      location: "Anganwadi Center",
      description: "Meeting to discuss formation of new self-help groups and skill development programs.",
    },
    alerts: [
      {
        type: "urgent",
        icon: '<i class="fas fa-child"></i>',
        title: "Missing Child Alert",
        description: "10-year-old Raju missing since morning - Contact authorities if seen",
        time: "3 hours ago",
      },
    ],
    activeIssues: [],
    resolvedIssues: [],
    panchayatMembers: [],
    panchayatDecisions: [],
    mediaGallery: [],
    activeInitiatives: [],
    completedInitiatives: [],
  },
  songarh: {
    name: "Songarh Village",
    population: 1850,
    households: 430,
    issues: 6,
    nextEvent: {
      title: "Village Water Management Meeting",
      date: "Thursday, 19 Oct 2023 - 4:00 PM",
      location: "Gram Panchayat Hall",
      description: "Discussion on water conservation methods and distribution schedule for winter.",
    },
    alerts: [
      {
        type: "urgent",
        icon: '<i class="fas fa-exclamation-circle"></i>',
        title: "Water Supply Interruption",
        description: "Water supply will be off for maintenance from 10 AM to 4 PM tomorrow",
        time: "6 hours ago",
      },
    ],
    activeIssues: [],
    resolvedIssues: [],
    panchayatMembers: [],
    panchayatDecisions: [],
    mediaGallery: [],
    activeInitiatives: [],
    completedInitiatives: [],
  },
}
